### ISSUE TITLE
Can you add HTML inside shapes such as icons?

### ISSUE THREAD

**Issue by jdmagic21** [kimmobrunfeldt/progressbar.js#101]

**Comment by kimmobrunfeldt** [comment]
This is not possible with the current API. I've been planning to finalize this feature for a long time but haven't had time/use cases for that. To workaround the current API, see: https://github.com/kimmobrunfeldt/progressbar.js/issues/47#issuecomment-76932345

**Comment by kimmobrunfeldt** [comment]
I'll close this issue, this remains open https://github.com/kimmobrunfeldt/progressbar.js/pull/77

**Comment by A973C** [comment]
Hi @kimmobrunfeldt 
First of all, thank you for this great and simple plugin!
I'm currently using it with the semi circular option. It works great. Now I wanted to add an icon on my graph. So i've been using the dedicated html content ```<p class="progressbar-text">my icon</p>```. Works great too.
However, I'd like my icon to follow my graph progression instead of a fixed positionning.
Could you please tell me how to make it working?
Thank you
