### ISSUE TITLE
Demo suggestions

### ISSUE THREAD

**Issue by kimmobrunfeldt** [kimmobrunfeldt/progressbar.js#114]
I'm working on a new demo page for the project. I'd be open to add your demos to the new site. If you want to suggest a demo, comment to this issue with:
- Link to JSFiddle, you can fork this: http://jsfiddle.net/kimmobrunfeldt/a1osxLdj/3/
- Short description, max 27 chars
- Your name

Example of submission below. Demos will be attributed to the creator of course.

Current visual design of the new page looks like this:

![demo](https://cloud.githubusercontent.com/assets/1232405/13747489/209d3512-ea01-11e5-9015-e1844652b6f6.gif)

**Comment by kimmobrunfeldt** [comment]
* http://jsfiddle.net/kimmobrunfeldt/a1osxLdj/2/
* Thin circle
* Kimmo Brunfeldt

**Comment by obonyojimmy** [comment]
Kindly add demo of seting multiple progress animation via promise , ie given point x -z , move from point z-y , then y-z , also using promises in animate method , thanks !

**Comment by obonyojimmy** [comment]
@kimmobrunfeldt  , how did you achieve re-animating the progressbars when the progressbar animation has finished as in your examples ?

**Comment by kimmobrunfeldt** [comment]
You can examine the code of the demo page here: https://github.com/kimmobrunfeldt/progressbar.js/blob/gh-pages/scripts/index.js

**Comment by Kyamu56121** [comment]
@kimmobrunfeldt I have a sort of oddball issue.
I am trying to create a progress bar that starts in the center of a bar, and moves either left (up to -100) or right (up to +100). The standard line will start on the right and move left if a negative value is given when it is animated.

Do you have any suggestions for how I might go about this?

**Comment by martindefatte** [comment]
I've been having some issues using arrow functions ``step: (state, bar) => {`` – they don't seem to be supported in IE11.

**Comment by offthedome** [comment]
@kimmobrunfeldt I don't know if you answer the n00b questions :-) but I found an example of your timer I want to start from on jsfiddle, and I can't even get it to work by copying the entire frame and pasting it onto a separate page. I've also tried copying and pasting the three frames of code, including the obvious appropriate locations of html tags wherever they belong, but I still can't get it to work. Here's the jsfiddle page: https://jsfiddle.net/kimmobrunfeldt/72tkyn40/
Here's the page I'm testing the counter on (keeps changing because I'm still working on it): http://www.addressmunger.com/test/testcounter.php

**Comment by Elesmer** [comment]
Hi, I need help with your library, how do I get animations when a user jumps to it?

**Comment by dennischrist** [comment]
hi @kimmobrunfeldt

is is possible to rotate the starting point of the circle?
