### ISSUE TITLE
Glow Effect?

### ISSUE THREAD

**Issue by jsoncylu** [kimmobrunfeldt/progressbar.js#132]
This isn't an issue but I don't know where to ask this.

I'd like to add a glow effect to the stroke path, how would I do that? I was looking at this: http://stackoverflow.com/questions/9630008/how-can-i-create-a-glow-around-a-rectangle-with-svg

How would I add a filter to the svg?

Thanks!

**Comment by kimmobrunfeldt** [comment]
This was interesting question, I tried a few variations.

*First, remember that SVG filters are not supported e.g. in IE9: http://caniuse.com/#feat=svg-filters*

If that's fine, you have two options. Note that if the "glow"(blur) goes out of the SVG canvas, it won't look good. Beware that ProgressBar.js fits the shapes(e.g. Line, Circle) exactly to the canvas, so that the edges of the Circle will hit the SVG canvas edges. You have to either manually create the SVG your self, or try to fiddle with different options so that the glow wouldn't be cropped. You can hack the circle smaller than canvas by setting up a smaller `strokeWidth` and larger `trailWidth`, see option 2.

### 1. Use your own SVG

http://jsfiddle.net/1b4Leekg/

JS
```js
var path = new ProgressBar.Path('#path', {
  easing: 'easeInOut'
});
path.animate(1.0);  // Number from 0.0 to 1.0
```

HTML
```html
<div id="container">
  <svg viewBox="0 0 100 100" style="display: block; width: 100%;">
    <defs>
      <filter id="glow">
        <feGaussianBlur stdDeviation="2.5" result="coloredBlur"/>
        <feMerge>
          <feMergeNode in="coloredBlur"/>
          <feMergeNode in="SourceGraphic"/>
        </feMerge>
      </filter>
    </defs>

    <path d="M 50,50 m 0,-45 a 45,45 0 1 1 0,90 a 45,45 0 1 1 0,-90" stroke="#eee" stroke-width="1" fill="none"></path>
    <path id="path" filter="url(#glow)" d="M 50,50 m 0,-45 a 45,45 0 1 1 0,90 a 45,45 0 1 1 0,-90" stroke="#FCB03C" stroke-width="3" fill="none"></path>
  </svg>
</div>
```

### 2. Hack `strokeWidth` and `trailWidth`

*This only works with Circle and SemiCircle.*

http://jsfiddle.net/jhpwk5qz/

This works because:
* We make trail path bigger than strokeWidth and make trail path invisible, this leaves room for the "glow" in the SVG canvas.
* Add SVG filter to HTML and add id for the filter.
* Set `filter` css for the actual path inside SVG.

**JS**
```js
var path = new ProgressBar.Circle('#container', {
  easing: 'easeInOut',
  strokeWidth: 3,
  // Make trail path bigger but invisible
  trailWidth: 10,
  trailColor: 'rgba(0, 0, 0, 0.0)'
});
path.animate(1.0);  // Number from 0.0 to 1.0
```

**HTML**
```html
<div id="container"></div>

<svg>
  <defs>
    <filter id="glow">
      <feGaussianBlur stdDeviation="2.5" result="coloredBlur"/>
      <feMerge>
        <feMergeNode in="coloredBlur"/>
        <feMergeNode in="SourceGraphic"/>
      </feMerge>
    </filter>
  </defs>
</svg>
```

**CSS**
```css
#container {
    width: 100px;
    height: 100px;
}

#container > svg {
    width: 100%;
    display: block;
}

#container > svg > path:last-child {
    filter: url(#glow);
}
```

**Comment by jsoncylu** [comment]
Wow thanks for the quick response! I just tried option 2. Is there a way to have the trail width be equal to the stroke width but the "glow" leaks out of the trail width?
