### ISSUE TITLE
Can the color of path be gradient?

### ISSUE THREAD

**Issue by HiCrispy** [kimmobrunfeldt/progressbar.js#139]
I wanna get a circle path with gradient colors, but I see no relevant reference in api, and CSS3's gradient color mechanism does not work here.

**Comment by kimmobrunfeldt** [comment]
That would be a nice feature but unfortunately it seems that SVG doesn't support such gradient :/ http://stackoverflow.com/questions/14633363/can-i-apply-a-gradient-along-an-svg-path

Someone has done a gradient for a path https://bl.ocks.org/mbostock/4163057 but it can't be used with this library because the path consists of multiple <path> elements.

**Comment by HiCrispy** [comment]
@kimmobrunfeldt I've found a lib that can use gradient for path, thanks anyway.

**Comment by kimmobrunfeldt** [comment]
Ok nice, which library?

**Comment by HiCrispy** [comment]
A lib called circle-progress.js.
http://kottenator.github.io/jquery-circle-progress/
