### ISSUE TITLE
Issue On Setting Stop Position and Updateing the Bar

### ISSUE THREAD

**Issue by Behseini** [kimmobrunfeldt/progressbar.js#42]
Hi Kimmo,
This looks very nice and organized progress bar but I couldn't find out how to set up stop point for percentage presentation! For example let say how you can display %80 job done out of %100?
And also how to update the bar? For example in case of having an update button like this
 `$('#update').on('click', function(){
        circle.animate(0);
        circle.animate(1);
  });`
or on scroll based animation how can you re-animate the bar?

Thanks

**Comment by kimmobrunfeldt** [comment]
Hi!

I have by design delegated as much as possible to the library users so it stays generic enough. That's why there's no ready-made options to achieve things like "80% out of 100%".

If by stop point you mean that you want to display "human" readable progress like 20% out of 100% etc, you have to create the logic for that yourself. You have to create the string and pass it to **setText**. You can see plenty of example usages in http://kimmobrunfeldt.github.io/progressbar.js/.

You can bind scroll events and update the progress bar from the callback function. You have to manually calculate which way the scroll was done. For example you could always add 2 percentage values from scroll up event. You can get current value of progress bar with **.value()** method.
