### ISSUE TITLE
Keeping multiple circle in seperate column 

### ISSUE THREAD

**Issue by vivinblack** [kimmobrunfeldt/progressbar.js#53]
I am trying to keep 4 circle inside 4 column(25% width) in a row, instead of floating side by side all 4 circle appearing in single column underneath each . 

<div class="one-fourth alignleft"><div class="circle"></div></div>
<div class="one-fourth alignleft"><div class="circle"></div></div>
<div class="one-fourth alignleft"><div class="circle"></div></div>
<div class="one-fourth alignleft"><div class="circle"></div></div>

**Comment by kimmobrunfeldt** [comment]
Do you have text inside the Circles?
If you add text inside the progress bar, the library automatically sets `position: relative` for the progress bar container.

Can you show the JS, HTML and CSS of your case in e.g. JS fiddle? You can fork the simple JSFiddle linked in README.md: http://jsfiddle.net/kimmobrunfeldt/8xa87k31/

**Comment by vivinblack** [comment]
just see it here:  http://jsfiddle.net/8xa87k31/266/

**Comment by kimmobrunfeldt** [comment]
Ok. The selector doesn't work like with jQuery.
It uses [document.querySelector](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector) under the hood. That will match the *first* element with `.container-4` class. That's why all progress bars are added to the first container.

Do something like this instead: http://jsfiddle.net/xrbfw21o/

**Comment by vivinblack** [comment]
Mean I need to add unique data attribute or unique class to match the selection .At least I need to supply unique Id for each. Its really helpful . but i dont know whether its reliable while generating unknown number of circles using shortcode in theme.
