### ISSUE TITLE
Unable to set preserveAspectRatio

### ISSUE THREAD

**Issue by ZachSaucier** [kimmobrunfeldt/progressbar.js#57]
I need to change the SVG's `preserveAspectRatio` because of an IE issue.As it is now, I have to do `pbElem.svg.setAttribute("preserveAspectRatio", "xMinYMin");` I can't set it via CSS. 

Can we please get it added as a property option? Like `var pbElem = new ProgressBar.Line('.selector', { preserveAspectRatio: "xMinYMin"});`? Same for the other SVG properties

**Comment by ZachSaucier** [comment]
As it is now, I have to do `pbElem.svg.setAttribute("preserveAspectRatio", "xMinYMin");`

**Comment by kimmobrunfeldt** [comment]
Is there something wrong with the `pbElem.svg.setAttribute("preserveAspectRatio", "xMinYMin")`? I have made a decision to offer references to the underlying svg and path elements so that you can call their APIs. I could forwards some options directly to the svg, but then I'd have to list all available svg properties and maintain the list. I'd prefer not to.

**Comment by kimmobrunfeldt** [comment]
If more people want this, I can reconsider. For now, please use the setAttribute() method like you already did.
